---
title:    "Final Exam"
subtitle: "Bayesian Statistics"
author:   "Daniel Carpenter"
date:     "May 9, 2022"
fontsize: 12pt
geometry: margin=1in
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    toc_depth: 2
  # github_document:
  #   toc: yes
  #   number_sections: yes
  #   toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo    = TRUE,
	include = TRUE,
	message = FALSE,
	warning = FALSE,
	cache   = TRUE
)
```


Please place all answers in this document - use $\LaTeX$, R and Jags as needed. Answers to many qestions will be made dynamically through an R chunk.

# Question 1

## a)

## b)

## c)

## d)

## e)

## f)

### i)

### ii)

# Question 2

## a)

## b)

## c)

## d)

## e)

# Question 3

## a)

## b) 

## c)

## d)

## e)

# Question 4

## a)

## b) 

## c)

## d)

### 1)

### 2)

# Question 5

## a)

## b)

## c)

## d)

## e)



# Question 6


# Question 7

## a)

## b)

## c)

## d)



# Question 8


## a)

## b)

## c)

## d)

# Question 9

```{r data9}
dataList = list(x = c(-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 
3, 4, 5, 6, 7, 8, 9, 10), y = c(21.72, 20.41, 14.06, 14.6, 13.8, 
10.4, 8.22, 6.79, 4.92, 0.45, 4.57, 1.95, 10.14, 13.28, 21.88, 
18.88, 22.91, 23.53, 34.99, 35.07, 39.17), N = 21)
```

## b)

### i)

### ii)

### iii)

## c)

## d)

## e)




# Question 10

```{r}
x=50:80
set.seed(24)
y=10+2*x+rnorm(31,0,10)

xx=-15:15
set.seed(24)
yy=10+2*xx+rnorm(31,0,10)

```

## a)

## b)

### i)

### ii)



