---
title:    "Lab 4 - Bayes Box and R"
subtitle: "Bayesian Statistics"
author:   "Daniel Carpenter"
date:     "February 2022"
fontsize: 12pt
geometry: margin=1in
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document: 
    toc: TRUE
    number_sections: TRUE
  github_document: default
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

# Task `1`: 

## `a.` Classical Point Estimate for 𝜃
```{r 1a, echo=TRUE, message=FALSE}
# Probability of success given N number of trials
from = 0
to   = 1
n    = 10

theta <- seq(from, to, length = n)

# Point Estimate for Theta
pointEst <- mean(theta)
pointEst
```

## `b.` Confidence Interval using 𝜃

`i.` Find classical 95% confidence interval using $\theta$
```{r 1bi, echo=TRUE, message=FALSE}
classicalEst <- pointEst + c(-1, 1) * 1.95 * sqrt(pointEst*(1 - pointEst) / n)
classicalEst
```


`ii.` Interpretation of the Interval above
```{r 1bii, echo=TRUE, message=FALSE}
print(paste0("We can be 95% confident that the true value of theta will be between ",
             round(classicalEst[1], 4), " and ", round(classicalEst[2], 4), 
             " (rounded to 4 decimal places) if repreated samples were taken."))
```

`iii.` How many sample are used to make the interval?
```{r 1biii, echo=TRUE, message=FALSE}
print(paste0("There are ", n, " number of samples used to make the interval."))
```

`iv.` How many samples are assumed to give the interpretation?
```{r 1biv, echo=TRUE, message=FALSE}
print(paste0("An infinite number of samples are assumed to give this interpretation"))
```

---

<br>

# Task `2`: 

## `a.`
```{r 2a, echo=TRUE, message=FALSE}
```

## `b.`
```{r 2b, echo=TRUE, message=FALSE}
```

## `c.`
```{r 2c, echo=TRUE, message=FALSE}
```

## `d.`
```{r 2d, echo=TRUE, message=FALSE}
```

## `e.`
```{r 2e, echo=TRUE, message=FALSE}
```

## `f.`
```{r 2f, echo=TRUE, message=FALSE}
```


---

<br>

# Task `3`: 

## `a.`
```{r 3a, echo=TRUE, message=FALSE}
```

## `b.`
```{r 3b, echo=TRUE, message=FALSE}
```

## `c.`
```{r 3c, echo=TRUE, message=FALSE}
```


---

<br>

# Task `4`: 

## `a.`
```{r 4a, echo=TRUE, message=FALSE}
```

## `b.`
```{r 4b, echo=TRUE, message=FALSE}
```


---

<br>

# Task `5`: 

## `a.`
```{r 5a, echo=TRUE, message=FALSE}
```

## `b.`
```{r 5b, echo=TRUE, message=FALSE}
```

