---
title:    "Lab 6 - Gibbs Sampling (MCMC)"
subtitle: "Bayesian Statistics"
author:   "Daniel Carpenter"
date:     "March 2022"
fontsize: 12pt
geometry: margin=1in
output:
  html_document:
    toc: yes
    toc_float: yes
---

## Task 1
> Create a function that carries out MCMC simulation using a vector h made of the prior*likelihood.

```{r 1, echo=TRUE, message=FALSE}
# This function makes discrete simulations from a posterior with any number of h values
# n=nu of iterations
# You can embellish this function
mydmcmc <- function(n=10000, h,...){
  alpha<-c() # holds transition probs
  alpha[1]<-1
  u<-c() # holds uniform values
  u[1]<-1
  post<-c()# post sample
  prop<-c() # vec of proposed states 1s and 2s
  prop[1]=1 # initial state
  post[1]=prop[1]
  for(i in 2:n){ # starts at 2 because initial value given above
    # proposal state 
    prop[i]=sample(1:length(h),1,replace=TRUE)
    # calculate alpha
    # notice h[prop[i]] gives the actual value of h
    alpha[i]=min(1,h[prop[i]]/h[post[i-1]])
    # to calculate accepting proposal with prob alpha
    # select a random value from  a uniform (0,1)
    u[i]=runif(1)
    if(u[i]<=alpha[i]){post[i]<-prop[i]}
    else{post[i]<-post[i-1]}
  }
  res<-matrix(c(prop,u,alpha,post ),nc=4,nr=n,byrow=FALSE)
  sim<-table(post)/n
  # windows only works with a pc
  # quartz with macs
  # dev.new(noRStudioGD = TRUE) # or quartz() 
  
  postexact<-h/sum(h)

  
  # PLOTS ======================================================================
  
    require(tidyverse)
    require(ggplot2)
  
  # Create a simple theme for reuse
  myTheme <- theme_minimal() + theme(text = element_text(color = '#666666'),
                                     panel.grid.major = element_blank())
  
  
  # Make the iter vector a data frame
  iterOut <- as.data.frame(res) %>% 
    mutate(numIterations = row_number()) 
  
    
  # Simulation output ------------------------------------------------------
  simPlot <- ggplot(data.frame(sim), 
                    aes(x=post, y = Freq)) + 
    
    # COlumn Chart of the post estimated
    geom_col( fill="lightblue", colour="lightblue4", alpha = 0.6) +
    
    # Line of the Posterior Exactly Calculated
    
    
    
    # Theme
    myTheme + 
    
    # Labels
    labs(title = paste("Discrete MCMC Similation Output using simR()\nAssumes",
                       "Uniform Prior dist. over ", numThetaValues, 
                       " values of theta.\nProb. ", x, 
                       "with", n, "bernoulli trials - Daniel Carpenter"),
         y = "Frequency",
         x = "Proposed h's")
    # Now print the plot
    print(simPlot)
    
    
  
  # Trace Plot  ------------------------------------------------------------
    tracePlot <- ggplot(data=iterOut,
           aes(x=numIterations, y=V4)) +
      
      # Add the lines
      geom_line(color='lightblue3', alpha = 0.8) +
      
      # Add some points
      geom_point(color = 'lightblue4', size = 0.25, alpha = 0.1) + 
      
      # Theme and Labels
      myTheme +
      labs(title = "Trace Plot - Est. Posterior",
           subtitle = paste("Assumes Uniform Prior dist. over ", numThetaValues, 
                            " values of theta.\nProb. ", x, 
                            "with", n, "bernoulli trials - Daniel Carpenter"),
           x = "Number of Iterations",
           y = "Posterior Value")
    
    # Now print the aboce plot
    print(tracePlot)
    
    
  # Show Alpha  -------------------------------------------------------------
    alphaPlot <- ggplot(data=iterOut,
           aes(x=numIterations, y=V3)) +
      
      # Add the lines
      geom_line(color='lightblue3', alpha = 0.8) +
      
      # Add some points
      geom_point(color = 'lightblue4', size = 0.25, alpha = 0.1) + 
      
      # Theme and Labels
      myTheme +
      labs(title = "Trace Plot - Est. Alpha",
           subtitle = paste("Assumes Uniform Prior dist. over ", numThetaValues, 
                            " values of theta.\nProb. ", x, 
                            "with", n, "bernoulli trials - Daniel Carpenter"),
           x = "Number of Iterations",
           y = "Alpha Value")
    
    # Now print the plot
    print(alphaPlot)
    
    
  # Show Alpha  -------------------------------------------------------------
    propOut <- ggplot(data=iterOut,
           aes(x=numIterations, y=V1)) +
      
      # Add the lines
      geom_line(color='lightblue3', alpha = 0.8) +
      
      # Add some points
      geom_point(color = 'lightblue4', size = 0.25, alpha = 0.1) + 
      
      # Theme and Labels
      myTheme +
      labs(title = "Trace Plot - The Proposal",
           subtitle = paste("Assumes Uniform Prior dist. over ", numThetaValues, 
                            " values of theta.\nProb. ", x, 
                            "with", n, "bernoulli trials - Daniel Carpenter"),
           x = "Number of Iterations",
           y = "Alpha Value")
    
    # Now print the plot
    print(propOut)
    
    
  # The returned output is a list 
  # Use obj$ to obtain whatever interests you
  return(list(iter=res,sim=sim,postexact=postexact,post=post) )
}


# Create a function to establish a Uniform Binomial Experiment
getH <- function(numThetaValues, x, n) {
  
  ## Form uniform probability
  theta <- seq(0, 1, length = numThetaValues)
  
  ## Calculate prior assuming uniform distribution
  prior = rep(1/numThetaValues, numThetaValues)
  
  ## Calculate the likelihood
  likelihood  = dbinom(x=x, size=n, prob=theta)
  
  ## Calculate the Prior x the Likelihood
  h <-  prior * likelihood
  
  return(h)
}


# Inputs for getH()
numThetaValues = 40
x = 4
n = 10

# Call mydmcmc and add some extras to the plot
mydmcmcOutput <- mydmcmc(n=10000, h=getH(numThetaValues, x, n))

# Iteration output
head(mydmcmcOutput$iter)

# Simulation output
head(mydmcmcOutput$sim) 

# Actual Posterior
head(mydmcmcOutput$postexact) 

# Estimated Posterior Posterior
head(mydmcmcOutput$post) 
```


---

<br>

## Task 2



---

<br>

## Task 3
> Run and Jags Exampl

* Note copied and pasted into this file for ease of printing output when knitting `rmd` file

```{r 3, echo=TRUE, message=FALSE}
# Jags-ExampleScript-lab6.R 

# Optional generic preliminaries:
graphics.off() # This closes all of R's graphics windows.
rm(list=ls())  # Careful! This clears all of R's memory!

# Load the functions used below:
source("DBDA2E-utilities.R") # Must be in R's current working directory.
obj = require(rjags)               # Must have previously installed package rjags.
obj
fileNameRoot="JAGS_Lab6_Task3_Ouput_Folder/" # For output file names.
dir.create(fileNameRoot)

# Define the model:
modelString = "
model {
  y[1:2] ~ dmnorm.vcov(mu[1:2],Sigma[1:2,1:2])
Sigma[1,1]<- 4
Sigma[2,2]<- 16
Sigma[1,2]<- 0.2*2*4
Sigma[2,1]<- 0.2*2*4
mu[1]<-10
mu[2]<-5
}
" # close quote for modelString
writeLines( modelString , con=paste0(fileNameRoot, "TEMPmodel.txt" ))

# Run the chains:
jagsModel = jags.model( file=paste0(fileNameRoot, "TEMPmodel.txt" )  , 
                        n.chains=3 , n.adapt=500 )
update( jagsModel , n.iter=5000 )
codaSamples = coda.samples( jagsModel , variable.names=c("y[1]","y[2]") ,
                            n.iter=3334 )
save( codaSamples , file=paste0(fileNameRoot,"Mcmc.Rdata") )

# Examine the chains:
# Convergence diagnostics:
diagMCMC( codaObject=codaSamples , parName="y[1]" )
saveGraph( file=paste0(fileNameRoot,"y[1]") , type="jpeg" )

diagMCMC( codaObject=codaSamples , parName="y[2]" )
saveGraph( file=paste0(fileNameRoot,"y[2]") , type="jpeg" )

# Posterior descriptives:
openGraph()
par( mar=c(3.5,0.5,2.5,0.5) , mgp=c(2.25,0.7,0) )
plotPost( codaSamples[,"y[1]"] , main="x[1]" , xlab=bquote(x[1]) )
saveGraph( file=paste0(fileNameRoot,"x[1]") , type="jpeg" )

# Re-plot with different annotations:
openGraph()
plotPost( codaSamples[,"y[2]"] , main="y[2]" , xlab=bquote(y[2]) )
saveGraph( file=paste0(fileNameRoot,"y[2]") , type="jpeg" )

# Process the MCMC samples in a specialist package
library(ggmcmc)
s = ggs(codaSamples) # This formats the samples for the package
dev.new()
ggs_density(s)
dev.new()
ggs_pairs(s)
```

